name: Deploy to BE Bang Jenggot's POS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.BJGPOS_HOST }}
          username: ${{ secrets.BJGPOS_USER }}
          key: ${{ secrets.BJGPOS_KEY }}
          port: 22
          script: |
            echo "🚀 Deploying Backend..."

            cd /home/be-banggjenggotpos/htdocs/be-bangjenggotspos.nexttechenterprise.site || exit

            git fetch origin
            git reset --hard origin/main

            npm install

            pm2 startOrReload ecosystem.config.cjs --update-env
